export const basketballPlayers = [
  {
    name: "LeBron James",
    position: "Small Forward",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/2544.png",
  },
  {
    name: "Stephen Curry",
    position: "Point Guard",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/201939.png",
  },
  {
    name: "Kevin Durant",
    position: "Power Forward",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/201142.png",
  },
  {
    name: "Giannis Antetokounmpo",
    position: "Power Forward",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/203507.png",
  },
  {
    name: "Michael Jordan",
    position: "Point Guard",
    active: false,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/893.png",
  },
  {
    name: "Kawhi Leonard",
    position: "Small Forward",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/202695.png",
  },
  {
    name: "James Harden",
    position: "Shooting Guard",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/201935.png",
  },
  {
    name: "Damian Lillard",
    position: "Point Guard",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/203081.png",
  },
  {
    name: "Kobe Bryant",
    position: "Shooting Guard",
    active: false,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/977.png",
  },
  {
    name: "Joel Embiid",
    position: "Center",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/203954.png",
  },
  {
    name: "Nikola Jokic",
    position: "Center",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/203999.png",
  },
  {
    name: "Jimmy Butler",
    position: "Small Forward",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/202710.png",
  },
  {
    name: "Luka Doncic",
    position: "Point Guard",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/1629029.png",
  },
  {
    name: "Anthony Davis",
    position: "Power Forward",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/203076.png",
  },
  {
    name: "Paul George",
    position: "Small Forward",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/202331.png",
  },
  {
    name: "Kareem Abdul-Jabbar",
    position: "Center",
    active: false,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/76003.png",
  },
  {
    name: "Chris Paul",
    position: "Point Guard",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/101108.png",
  },
  {
    name: "Zion Williamson",
    position: "Power Forward",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/1629627.png",
  },
  {
    name: "Jayson Tatum",
    position: "Small Forward",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628369.png",
  },
  {
    name: "Devin Booker",
    position: "Shooting Guard",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/1626164.png",
  },
  {
    name: "Trae Young",
    position: "Point Guard",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/1629027.png",
  },
  {
    name: "Karl-Anthony Towns",
    position: "Center",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/1626157.png",
  },
  {
    name: "DeMar DeRozan",
    position: "Small Forward",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/201942.png",
  },
  {
    name: "Shai Gilgeous-Alexander",
    position: "Point Guard",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628983.png",
  },
  {
    name: "Victor Wembanyama",
    position: "Center",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/1641705.png",
  },
  {
    name: "Tyrese Haliburton",
    position: "Point Guard",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/1630169.png",
  },
  {
    name: "Jalen Brunson",
    position: "Point Guard",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/260x190/1628973.png",
  },
  {
    name: "Domantas Sabonis",
    position: "Power Forward",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/260x190/1627734.png",
  },
  {
    name: "Bam Adebayo",
    position: "Center",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/260x190/1628389.png",
  },
  {
    name: "Donovan Mitchell",
    position: "Shooting Guard",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/260x190/1628378.png",
  },
  {
    name: "Jaylen Brown",
    position: "Shooting Guard",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/260x190/1627759.png",
  },
  {
    name: "De'Aaron Fox",
    position: "Point Guard",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/260x190/1628368.png",
  },
  {
    name: "Cade Cunningham",
    position: "Point Guard",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/260x190/1630595.png",
  },
  {
    name: "Scottie Barnes",
    position: "Small Forward",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/260x190/203084.png",
  },
  {
    name: "Brandon Ingram",
    position: "Small Forward",
    active: true,
    image: "https://cdn.nba.com/headshots/nba/latest/260x190/1627742.png",
  },
];
