import {
  IconCalendarEvent,
  IconCalendarTime,
  IconBriefcase,
  IconClockX,
  IconBuildings,
  IconAlarm,
  IconClockPlay,
  IconCalculator,
  IconLayoutDashboard,
  IconCalendarMonth,
  IconId,
  IconArchive,
  IconNotes,
  IconTimeline,
  IconHourglass,
  IconUsersGroup,
  IconSitemap,
  IconCoins,
  IconCash,
  IconCashRegister,
  IconFileChart,
  IconReplace,
  IconProgressDown,
  IconClock2,
  IconChartInfographic,
  IconFileReport,
  IconChartHistogram,
  IconChartLine,
  IconMoneybag
} from "@tabler/icons-react";
import { ChartColumn, HandCoins, SquareChartGantt } from "lucide-react";


export const iconMap: unknown = {
  IconCalendarEvent: IconCalendarEvent,
  IconCalendarTime: IconCalendarTime,
  IconBriefcase: IconBriefcase,
  IconClockX: IconClockX,
  IconBuildings: IconBuildings,
  IconAlarm: IconAlarm,
  IconClockPlay: IconClockPlay,
  IconCalculator: IconCalculator,
  IconLayoutDashboard: IconLayoutDashboard,
  IconCalendarMonth: IconCalendarMonth,
  IconId: IconId,
  IconArchive: IconArchive,
  IconNotes: IconNotes,
  IconTimeline: IconTimeline,
  IconHourglass: IconHourglass,
  IconUsersGroup: IconUsersGroup,
  IconSitemap: IconSitemap,
  IconCoins: IconCoins,
  IconCash: IconCash,
  IconCashRegister: IconCashRegister,
  IconFileChart: IconFileChart,
  HandCoins: HandCoins,
  IconReplace: IconReplace,
  IconProgressDown: IconProgressDown,
  IconClock2: IconClock2,
  ChartColumn: ChartColumn,
  IconChartInfographic: IconChartInfographic,
  IconFileReport: IconFileReport,
  IconChartHistogram: IconChartHistogram,
  SquareChartGantt:SquareChartGantt,
  IconChartLine:IconChartLine,
  IconMoneybag:IconMoneybag
};
