import {
  IconCalendarEvent,
  IconCalendarTime,
  IconBriefcase,
  IconClockX,
  IconBuildings,
  IconAlarm,
  IconClockPlay,
  IconCalculator,
  IconLayoutDashboard,
  IconCalendarMonth,
  IconId,
  IconArchive,
  IconNotes,
  IconTimeline,
  IconHourglass,
} from "@tabler/icons-react";

export const iconMap: any = {
  IconCalendarEvent: IconCalendarEvent,
  IconCalendarTime: IconCalendarTime,
  IconBriefcase: IconBriefcase,
  IconClockX: IconClockX,
  IconBuildings: IconBuildings,
  IconAlarm: IconAlarm,
  IconClockPlay: IconClockPlay,
  IconCalculator: IconCalculator,
  IconLayoutDashboard: IconLayoutDashboard,
  IconCalendarMonth: IconCalendarMonth,
  IconId: IconId,
  IconArchive: IconArchive,
  IconNotes: IconNotes,
  IconTimeline: IconTimeline,
  IconHourglass: IconHourglass,
};
